service: serverless-super-google-photos

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
  savePictures:
    handler: handler.savePictures
    events:
      - http:
          path: save/pictures
          method: get
plugins:
  - serverless-offline
